import math
import os
import sys
from kilogram import KiloGram



documents = list()
ngrams = list()
bucket = list()
stride = 2
lipsum = ["Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?"]


lip_sum = ["Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sagittis in erat nec rutrum. Morbi dignissim sem id ipsum ultricies mollis. Duis euismod mauris ac ex commodo mollis. Duis ut ipsum et mauris malesuada ullamcorper vel eget tortor. Suspendisse ac orci in nibh sollicitudin efficitur posuere vel lacus. Phasellus luctus sapien arcu, ut viverra mauris pharetra nec. Maecenas metus mi, vehicula non sem ut, venenatis tristique urna. Suspendisse erat est, egestas varius nibh at, dictum imperdiet erat. Donec in orci at nibh porttitor blandit id eget mauris. Nulla eu quam tristique, iaculis metus eget, convallis urna. Fusce non est tincidunt, blandit turpis quis, posuere est. Nam volutpat nulla ac sapien condimentum, ut blandit erat viverra. Maecenas suscipit enim elementum imperdiet tempor.",
"Nunc semper ipsum at velit convallis, id placerat ex dictum. Sed in ornare enim. In vel imperdiet tellus. Fusce eu condimentum tellus. Phasellus auctor, neque ut facilisis lobortis, est libero auctor ligula, sit amet congue justo sem et est. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur porta pellentesque tortor nec consequat. Ut commodo, ante fermentum scelerisque placerat, nunc mi pellentesque libero, in lacinia magna urna ac libero. Praesent eget cursus dolor, vel tempus nisi. In congue hendrerit tellus in gravida. Etiam at lorem lectus. Cras lobortis odio eros, eu elementum tellus porttitor sit amet. Curabitur laoreet lectus in quam congue, sit amet tincidunt risus ullamcorper. Aenean consectetur est a imperdiet posuere.",
"Praesent iaculis pellentesque tellus, vel tincidunt justo fermentum id. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse non varius tortor. Donec sed convallis est, id mattis leo. Integer gravida justo id nunc gravida elementum at non diam. Vestibulum sollicitudin nisi eget enim dapibus interdum. Nulla quis justo est. Nullam molestie sagittis dignissim. Nullam leo lacus, porttitor ut mi nec, pharetra lobortis nibh. Ut non pharetra nisl, eu pulvinar nibh. Donec elementum, ante sit amet aliquet tristique, ex libero cursus dolor, euismod efficitur quam ante quis elit. Pellentesque in elit et lacus gravida imperdiet eu id risus.",
"Maecenas maximus enim non auctor tempus. Nulla a eros ut libero efficitur dictum id non ante. Praesent egestas nulla a dui volutpat tempus eget sit amet lacus. In hendrerit non massa ut finibus. Morbi egestas ornare magna vitae dignissim. Maecenas eget velit auctor, lacinia lectus id, dignissim massa. Vivamus dapibus elementum aliquam. Phasellus luctus dui in orci maximus, at scelerisque quam gravida. Quisque finibus quam quis consequat pulvinar. Proin vitae odio a purus sagittis efficitur. Maecenas at pretium leo, convallis cursus elit.",
"Proin porta scelerisque dolor vel euismod. Quisque vel elementum turpis, ut dignissim magna. Sed eget leo ipsum. Praesent in fermentum orci. Suspendisse potenti. Aliquam cursus nibh ligula, vitae bibendum sem euismod sit amet. Vivamus at sollicitudin orci. Nulla luctus nisl lorem, ut ultricies augue vulputate dapibus. Morbi commodo sit amet nunc nec fermentum. Proin eu diam at velit commodo sollicitudin. Maecenas eget nulla feugiat, blandit enim in, dictum felis. Duis dapibus massa sed vestibulum consectetur. Nullam nec tempor quam, a vulputate tellus. Duis accumsan laoreet nisi, et fringilla elit pharetra a.",
"Vivamus erat lorem, euismod vitae massa sit amet, faucibus malesuada tellus. Pellentesque pretium vehicula libero, eu posuere ligula venenatis eget. Duis blandit commodo tellus, id semper elit lacinia hendrerit. Proin convallis at lectus in porta. Sed condimentum enim vitae enim sodales imperdiet. Phasellus nec lectus id orci placerat faucibus non ac dolor. Aliquam nibh nisl, condimentum vitae pellentesque at, consequat vitae dui. Sed malesuada sed nulla sed bibendum. Ut gravida vestibulum dolor, vel vestibulum nulla elementum dictum. Phasellus finibus mi a lorem mollis maximus. Pellentesque laoreet lorem auctor augue tincidunt hendrerit. Cras vel dictum odio. Morbi ut pulvinar mauris, ac commodo ex. Donec aliquam ipsum sed leo pulvinar, nec accumsan dui tincidunt. Phasellus in mauris libero.",
"Pellentesque nec urna tempor, porttitor libero non, commodo sapien. Duis ut elementum purus. Phasellus varius massa vestibulum odio hendrerit consectetur. Etiam porttitor vehicula nunc id consectetur. Nullam tempor purus eu ornare cursus. Donec suscipit varius mi quis venenatis. Aenean vel sem nibh. Sed aliquet pulvinar erat non commodo. Nam ut mauris enim. Suspendisse potenti. Praesent laoreet dui erat, vitae luctus tellus dictum a.",
"Sed elementum scelerisque turpis a tristique. Pellentesque interdum elementum lacus, id condimentum felis consequat vel. Praesent diam neque, gravida id rhoncus et, bibendum a metus. Morbi lobortis quam massa, id imperdiet ligula posuere ac. Praesent convallis, nisi in suscipit aliquam, libero felis faucibus felis, a maximus mi orci et purus. Donec pellentesque vestibulum vestibulum. Aenean sodales suscipit nulla, sit amet eleifend nulla cursus ut. Mauris vel orci elementum, finibus ipsum quis, vehicula enim. Phasellus et tellus in ante pretium hendrerit sit amet et erat. Donec bibendum tincidunt ornare. Nam scelerisque libero quis egestas congue.",
"Nulla condimentum leo at eros sagittis cursus. Ut id cursus nisl. Nullam elementum dui sed rhoncus faucibus. Cras vitae vulputate nunc. Maecenas ac posuere quam, sed feugiat ex. Cras vehicula egestas sapien, quis viverra est semper sed. Morbi aliquet urna tortor, vel auctor diam venenatis et. Donec a pulvinar nulla.",
"Phasellus bibendum, sem fringilla consequat tincidunt, velit lorem hendrerit mi, vitae ornare felis quam eu dolor. Donec nec feugiat turpis. Nullam ut commodo enim, et semper tortor. Mauris pharetra viverra odio. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis non odio convallis, sollicitudin felis sed, ultrices justo. Vestibulum dapibus convallis urna in maximus.",
"Nam nulla elit, vulputate ac risus at, viverra viverra lacus. Donec et faucibus orci, vulputate volutpat velit. Sed a felis purus. Etiam quis justo tristique, pulvinar arcu et, dapibus lacus. Praesent in massa quam. Maecenas hendrerit semper ultricies. Sed a interdum nisi. Sed nec erat eu risus vestibulum vehicula vel in mauris. Duis sagittis ante erat, vitae dapibus massa varius sed. Suspendisse potenti. Suspendisse potenti. Ut velit turpis, pellentesque ac neque ut, sollicitudin consectetur metus. In hac habitasse platea dictumst. Quisque sit amet tellus efficitur ipsum pharetra aliquam vitae vitae libero. Etiam ut luctus libero, ut fermentum orci. Nam venenatis dolor eget posuere mollis.",
"Nulla scelerisque metus urna, vel lacinia augue ultrices nec. Cras porttitor, elit a congue rutrum, urna risus cursus arcu, mollis facilisis diam magna at tellus. In vehicula tortor eget dui sollicitudin eleifend. Praesent mauris tortor, placerat quis lobortis quis, tincidunt ac quam. Cras ut gravida est, quis dictum eros. Duis aliquet nunc eu varius gravida. Sed ac luctus purus, a faucibus enim. Maecenas vitae cursus felis. Aliquam placerat sed metus eget fringilla. Curabitur vitae pulvinar dolor, sit amet tincidunt risus. Morbi scelerisque aliquet est sed molestie. Sed fringilla ligula quis dui fringilla tristique.",
"Duis nec fringilla enim. Curabitur viverra purus sed metus mattis, ut fermentum tortor gravida. Morbi dictum nisl non bibendum tempor. Vivamus volutpat faucibus nunc, aliquet aliquam leo consequat at. Fusce eget mattis sapien. Sed malesuada risus quis ligula tincidunt auctor. Integer congue placerat elit, malesuada malesuada enim mollis sit amet. Fusce a ipsum mollis, scelerisque sapien a, semper tellus. Proin quis laoreet nisl. Mauris rutrum ante vel pharetra vestibulum. In ac nulla elementum, hendrerit nibh et, porttitor diam. Quisque eleifend quam nisl, ut porta ex efficitur egestas. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus bibendum venenatis ullamcorper. Donec vitae sodales velit.",
"Aliquam erat volutpat. Sed suscipit aliquam dui, ut laoreet quam congue quis. Aliquam erat volutpat. Vivamus lobortis mattis feugiat. Proin commodo consectetur diam sed semper. Proin eget magna id orci elementum iaculis. Curabitur non neque non arcu commodo dictum. Suspendisse nec massa nec nibh pretium gravida.",
"Morbi sodales iaculis dapibus. Sed vel lectus nec mauris condimentum suscipit ac sit amet mauris. Mauris dictum aliquet consectetur. Aenean vitae dignissim nulla, id molestie lacus. Morbi egestas, arcu ac pulvinar varius, ante ligula cursus augue, egestas faucibus nisi mi sit amet est. Nunc vel mi vel sem finibus lacinia in quis est. Nunc quis dui quis odio tincidunt malesuada. In libero ex, bibendum vel aliquet sit amet, euismod tincidunt tellus. Duis in maximus sapien.",
"Mauris sed consectetur leo. Suspendisse at magna sit amet neque rutrum laoreet. Sed tempor eros quam, ut viverra est elementum ac. Duis lobortis enim diam, eget suscipit augue dapibus a. In commodo ipsum vitae dolor molestie blandit. Cras mattis turpis eu aliquet suscipit. Cras vitae ultrices eros. Donec auctor nisi nunc, ultricies ullamcorper libero aliquet ut. Aliquam ut eros odio. Nullam maximus tincidunt urna eu maximus. Pellentesque ac risus malesuada, gravida sem ut, posuere orci. Integer ac vulputate tortor, a fringilla quam. Nam elit lectus, scelerisque id semper a, varius interdum quam.",
"Pellentesque elementum suscipit convallis. Curabitur at diam faucibus, sodales leo in, pulvinar arcu. Suspendisse ut vestibulum dolor. Suspendisse malesuada dignissim libero. Nunc varius metus et tortor lacinia fringilla in eu mi. Suspendisse non pulvinar velit. Nulla consequat imperdiet tortor. Suspendisse porta leo erat, sed fermentum tellus tempor eu.",
"Etiam dictum felis ut sem blandit aliquet. Aliquam ut neque eu velit suscipit eleifend at sollicitudin metus. Mauris semper magna libero. Fusce vestibulum elementum libero, eget congue ante elementum vehicula. Duis mattis vel lacus vel viverra. Aenean sollicitudin justo id placerat rhoncus. Nullam eu mollis ipsum, nec volutpat nibh. Nulla facilisi. Vivamus quis ultrices elit.",
"Sed dictum ultricies tristique. Nunc rutrum leo arcu. Integer facilisis purus sit amet est condimentum pellentesque. Nulla dignissim id est vel eleifend. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Morbi sed elit sit amet odio volutpat bibendum a non turpis. Vivamus hendrerit, arcu quis imperdiet efficitur, mauris magna blandit nulla, quis viverra metus mauris sit amet mauris. Morbi vestibulum orci ut efficitur ullamcorper. Suspendisse lacinia ullamcorper massa sed luctus. Quisque sit amet ante a diam blandit mollis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam vitae dignissim tortor, dapibus gravida arcu.",
"Aliquam in pretium est. In hac habitasse platea dictumst. Aenean iaculis turpis in sodales malesuada. Proin semper vestibulum leo, vel commodo elit sollicitudin convallis. Suspendisse non convallis nisl. Praesent semper libero quis placerat fringilla. Aenean nec orci maximus, laoreet leo vel, lacinia lorem. Morbi tincidunt sagittis feugiat. Cras sit amet nibh a ante congue porttitor et sed ante. Morbi mattis lorem eget velit interdum tristique. Integer lobortis, magna at vehicula porttitor, mauris est finibus risus, ac facilisis ex risus et elit. Morbi facilisis blandit nunc tristique rhoncus. Vivamus id purus dui. Nam porttitor blandit nulla pulvinar volutpat. "]

ngrams_1 = ["n", "o", "r", "m", "u", "a", "o", "e", "i"]
ngrams_2 = ["no", "on", "or", "mo", "ut", "la", "do", "ed", "ei"]
ngrams_3 = ["nos", "son", "ore", "mol", "uta", "lan", "dol", "sed", "qui"]
ngrams_4 = ["nsec", "sono", "dicta", "dolo", "aut", "labr", "proi", "illu", "lupt"]

'''
First phase - KiloGram finds the top k hashes for some corpora. Once the top k hashes are found we can then encode the bucket numbers of the top hashes into a matrix for a quantum computer to use.

Second phase  - This is where we would replace part of the KiloGram algorithm with Grovers Algorithm to do a linear search on this unsorted data (Grovers does not do as well on sorted data). 
'''


kg = KiloGram(lip_sum, ngrams_4)
num_gram = 0
topk_k = 0

topk_hashes = kg.rollingHash()

print("\n==== TOP K HASHES FOR N-GRAMS =====\n")
print("hash(crc32)\t|\tn-gram")
print("------------------------------------")
for key in topk_hashes:
    print(str(key) + "\t|\t" + topk_hashes[key])

print()





